"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_routes_1 = require("./user.routes");
var tweet_routes_1 = require("./tweet.routes");
var hello_routes_1 = require("./hello.routes");
var router = (0, express_1.Router)();
router.use('/hello', hello_routes_1.default);
router.use('/user', user_routes_1.default);
router.use('/tweet', tweet_routes_1.default);
exports.default = router;
